version: "3"
services:
  postgres:
    image: postgres:10
    restart: always
    environment:
      POSTGRES_USER: aiplay
      POSTGRES_PASSWORD: aiplay
    ports:
      - 5432:5432

  manager:
    build:
      context: .
      dockerfile: Dockerfile-hs
    command: [aiplay-manager]

  referee-tron:
    build:
      context: .
      dockerfile: Dockerfile-hs
    command: [aiplay-referee-tron]

  dummy-player:
    build:
      context: .
      dockerfile: Dockerfile-hs
    command: [aiplay-dummy-player]
