name:                aiplay
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/davazp/aiplay#readme
license:             BSD3
author:              David Vázquez Púa
maintainer:          davazp@gmail.com
copyright:           2018 David Vázquez Púa
extra-source-files:
  - README.md

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - containers

executables:
  aiplay-manager:
    source-dirs:      manager
    main:             Main.hs
    dependencies:
      - directory
      - filepath
      - postgresql-simple
      - cryptonite
      - memory

  aiplay-referee-tron:
    source-dirs:      referee-tron
    main:             Main.hs

  aiplay-dummy-player:
    source-dirs:      dummy-player
    main:             Main.hs
