name:                aiplay-tron
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/davazp/aiplay#readme
license:             BSD3
author:              David Vázquez Púa
maintainer:          davazp@gmail.com
copyright:           2018 David Vázquez Púa

dependencies:
  - base >= 4.7 && < 5
  - text
  - bytestring
  - containers

library:
  source-dirs: src/
  dependencies:
    - network
  
executables:
  aiplay-tron:
    main:             Main.hs
    dependencies:
      - aiplay-tron

tests:
  spec:
    source-dirs: test
    main: Spec.hs
    dependencies:
      - hspec
      - QuickCheck
      - aiplay-tron
